googlesign/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
from signin import views

from django.contrib.auth import views as auth_views

urlpatterns = [

    path('', TemplateView.as_view(template_name="social_app/index.html")),
    path('admin/', admin.site.urls),
    path('signin/', include('allauth.urls')),
    path('account/', views.accountSettings,name='accountSettings'),
    path('profile/', views.profile,name='profile'),
    path('post/', views.post,name='post'),
    path('logout/',views.logoutuser, name='logoutuser')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

signin/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Customer(models.Model):
	user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
	name = models.CharField(max_length=200, null=True)
	phone = models.CharField(max_length=200, null=True)
	email = models.CharField(max_length=200, null=True)
	profile_pic = models.ImageField(default="user.png", null=True,blank=True,upload_to='images')
	date_created = models.DateTimeField(auto_now_add=True, null=True)

	def __str__(self):
		return self.name
class Image(models.Model):
	user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
	caption=models.CharField(max_length=100)
	image=models.ImageField(upload_to="images")
	def __str__(self):
		return self.caption

signin/forms.py
from django.forms import ModelForm 
from .models import Customer,Image
  
class profileform(ModelForm): 
	class Meta: 
		model=Customer
		fields = '__all__'
		exclude=['user']


class ImageForm(ModelForm):
	class Meta:
		model=Image
		fields = '__all__'
		exclude=['user']

signin/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect 
from django.http import HttpResponse
# Create your views here.
from .models import Customer,Image
from .forms import profileform,ImageForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
# Create your views here.

def accountSettings(request):
    
    return render(request, 'social_app\index.html') 
def profile(request):
    try:
        customer = request.user.customer
        form = profileform(instance=customer)
        if request.method == 'POST': 
            form = profileform(request.POST, request.FILES,instance=customer)
            if form.is_valid:
                form.save()
    except Customer.DoesNotExist:
        profile = Customer.objects.create(user=request.user)
        customer = request.user.customer
        form = profileform(instance=customer)
        if request.method == 'POST': 
            form = profileform(request.POST, request.FILES,instance=customer)
            if form.is_valid:
                form.save()
    return render(request, 'social_app\index2.html',  {'form2':form})
@login_required
def post(request):
    form=ImageForm()
    if request.method == "POST":
        form=ImageForm(request.POST,request.FILES)
        if form.is_valid():
            newtodo=form.save(commit=False)
            newtodo.user = request.user
            form.save()
            form=ImageForm()
            return redirect('post')
    img=Image.objects.filter(user=request.user)
    return render(request,'social_app\index3.html',{"img":img,"form":form})
def logoutuser(request):
    if request.method =='POST':
        logout(request)
        return redirect('accountSettings')

templates/social_app/index.html
{% load socialaccount %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Google Registration</title>
  </head>
  <style>
  a {
    display: inherit;
    text-decoration: none;
}
	.profile-pic{
		max-width: 200px;
		max-height:200px;
		margin: 0 auto;
		border-radius: 50%;
	}
  .signup-w3ls {
    width: 50%;
    margin: 70px 25% 80%;
    padding: 0;
    display: table;
    position: relative;
}
.signup-agile1{
    width:100%;
    float:center;
}

.signup-w3ls .signup-agile1 .form-control {
    margin-bottom: 20px;
}
label.header {
    font-size: 16px;
    font-weight: 500;
    width: 215px;
    color: grey;
    margin-right:10px;
    text-align:justify;
    letter-spacing: 1px;
    text-transform: uppercase;
    display: inline-block;
    font-family: 'Nunito', sans-serif;
}
input#image,input#store_name, input#store_type,input#owner_type, input#website,input#contact_number,input#contact_email {
    padding:0 40px;
    width:40%;
    height:55px;
    border: 1px solid #dadada;
    color: grey;
    text-align:justify;
    outline: none;
    letter-spacing: 1px;
    font-size: 16px;
    font-weight:normal;
    font-family: 'Muli', sans-serif;
    border-radius:30px;
    -webkit-border-radius:30px;
    -moz-border-radius:30px;
    -o-border-radius:30px;
    -ms-border-radius:30px; 
}
input#image:focus,input#store_name:focus, input#store_type:focus,input#owner_type:focus, input#website:focus,input#contact_number:focus,input#contact_email:focus  {
    background-color:#f5f8fa !important;
    border:1px solid #dadada;
}
input::-webkit-input-placeholder {
color: grey;
} 
input:-moz-placeholder { /* Firefox 18- */
color: grey;  
} 
input::-moz-placeholder {  /* Firefox 19+ */
color: grey;  
} 
input:-ms-input-placeholder {  
color: grey;  
}
.register {
    background-color: lightgreen;
    width: 52%;
    height: 55px;
    border: none;
    margin-left: 233px;
    cursor: pointer;
    color: #fff;
    outline: none;
    font-size: 20px;
    font-weight: normal;
    text-transform: uppercase;
    transition: all 0.5s ease-in-out;
    -webkit-transition: all 0.5s ease-in-out;
    -moz-transition: all 0.5s ease-in-out;
    -o-transition: all 0.5s ease-in-out;
    border-radius: 30px;
    -webkit-border-radius: 30px;
    -moz-border-radius: 30px;
    -o-border-radius: 30px;
    -ms-border-radius: 30px;
    font-family: 'Muli', sans-serif;
}   
.register:hover {
    background-color:#36b051;
    color:#fff;
}
.signup-w3ls {
    width: 50%;
    margin: 70px 25% 80%;
    padding: 0;
    display: table;
    position: relative;
}
.signup-agile1{
    width:100%;
    float:center;
}

.signup-w3ls .signup-agile1 .form-control {
    margin-bottom: 20px;
}
label.header {
    font-size: 16px;
    font-weight: 500;
    width: 215px;
    color: grey;
    margin-right:10px;
    text-align:justify;
    letter-spacing: 1px;
    text-transform: uppercase;
    display: inline-block;
    font-family: 'Nunito', sans-serif;
}
input#image,input#store_name, input#store_type,input#owner_type, input#website,input#contact_number,input#contact_email {
    padding:0 40px;
    width:40%;
    height:55px;
    border: 1px solid #dadada;
    color: grey;
    text-align:justify;
    outline: none;
    letter-spacing: 1px;
    font-size: 16px;
    font-weight:normal;
    font-family: 'Muli', sans-serif;
    border-radius:30px;
    -webkit-border-radius:30px;
    -moz-border-radius:30px;
    -o-border-radius:30px;
    -ms-border-radius:30px; 
}
input#image:focus,input#store_name:focus, input#store_type:focus,input#owner_type:focus, input#website:focus,input#contact_number:focus,input#contact_email:focus  {
    background-color:#f5f8fa !important;
    border:1px solid #dadada;
}
input::-webkit-input-placeholder {
color: grey;
} 
input:-moz-placeholder { /* Firefox 18- */
color: grey;  
} 
input::-moz-placeholder {  /* Firefox 19+ */
color: grey;  
} 
input:-ms-input-placeholder {  
color: grey;  
}
.register {
    background-color: lightgreen;
    width: 52%;
    height: 55px;
    border: none;
    margin-left: 233px;
    cursor: pointer;
    color: #fff;
    outline: none;
    font-size: 20px;
    font-weight: normal;
    text-transform: uppercase;
    transition: all 0.5s ease-in-out;
    -webkit-transition: all 0.5s ease-in-out;
    -moz-transition: all 0.5s ease-in-out;
    -o-transition: all 0.5s ease-in-out;
    border-radius: 30px;
    -webkit-border-radius: 30px;
    -moz-border-radius: 30px;
    -o-border-radius: 30px;
    -ms-border-radius: 30px;
    font-family: 'Muli', sans-serif;
}   
.register:hover {
    background-color:#36b051;
    color:#fff;
}
.col-md-3 {
    margin: auto;
}
.register {
    display: inherit;
    margin: auto;
    width:30%;
}
</style>
  <body>

  
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Google Login</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  {% if user.is_authenticated %}
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
        <a class="nav-link" href="/account">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href='/profile'>Profile</a>
      </li>

      <li class="nav-item ">
        <a class="nav-link" href='/post'>Posts</a>
      </li>
    <li class="nav-item ">
    <form method='POST' action="{% url 'logoutuser' %}" class='ml-3' >
         {% csrf_token %}
      <button type='submit' class='btn btn-dark'>Logout</button></form>
  </li>
     </ul>
     </div>

</nav>
  <h1 align='center'>Welcome, {{ user.username }} !</h1>
  
<br>
<div class="row">
	<div class="col-md-3" align='center'>
		<div class="card card-body">
			<hr>
			<h3 style="text-align: center">Welcome</h3>
			<hr>
			<img class="profile-pic" src="{{request.user.customer.profile_pic.url}}" >
		  
		</div>
	</div>
  </div>
          
        </form>
    </div>
</div>
  <a   href='/profile'><input  class="register" type="button" value="Get Started"> </a> 

  {% else %}
     </div>

</nav>
 <div class="alert alert-danger" role="alert">
   <a href="{% provider_login_url 'google' %}" class="alert-link">Clike Here</a>Login with Google Accounts.
</div>
  {% endif %}
  

templates/social_app/index2.html
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Google Registration</title>
  </head>
  <style>
  .container {
    text-align: center;
    padding: 10px;
  }
    .profile-pic{
		max-width: 200px;
		max-height:200px;
		margin: 0 auto;
		border-radius: 50%;
	}
    .btn {
  transition-duration: 0.4s;
}

.btn:hover {
  background-color: #4CAF50; /* Green */
  color: white;
}
.register {
    background-color: lightgreen;
    width: 52%;
    height: 55px;
    border: none;
    margin-left: 233px;
    cursor: pointer;
    color: #fff;
    outline: none;
    font-size: 20px;
    font-weight: normal;
    text-transform: uppercase;
    transition: all 0.5s ease-in-out;
    -webkit-transition: all 0.5s ease-in-out;
    -moz-transition: all 0.5s ease-in-out;
    -o-transition: all 0.5s ease-in-out;
    border-radius: 30px;
    -webkit-border-radius: 30px;
    -moz-border-radius: 30px;
    -o-border-radius: 30px;
    -ms-border-radius: 30px;
    font-family: 'Muli', sans-serif;
}   
.register:hover,{
    background-color:#36b051;
    color:#fff;
}
#id_name:focus,#id_phone:focus,#id_email:focus {
  ~ #id_name,#id_phone,#id_email {
    position: absolute;
    top: 0;
    display: block;
    transition: 0.2s;
    font-size: 1rem;
    color: $primary;
    font-weight:700;    
  }
  padding-bottom: 6px;  
  font-weight: 700;
  border-width: 3px;
  border-image: linear-gradient(to right, $primary,$secondary);
  border-image-slice: 1;
}
/* reset input */
#id_name,#id_email,#id_phone{
  &:required,&:invalid { box-shadow:none; }
}
.form__group {
  position: relative;
  padding: 15px 0 0;
  margin-top: 10px;
  width: 50%;
}

#id_name,#id_email,#id_phone{
  font-family: inherit;
  width: 100%;
  border: 0;
  border-bottom: 2px solid $gray;
  outline: 0;
  font-size: 1.3rem;
  color: $white;
  padding: 7px 0;
  background: transparent;
  transition: border-color 0.2s;

  &::placeholder {
    color: transparent;
  }

  &:placeholder-shown ~ .form__label {
    font-size: 1.3rem;
    cursor: text;
    top: 20px;
  }
}
#id_profile_pic {
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
}

#id_profile_pic:hover {
  box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
}
#id_profile_pic {
    color: brown;
    background: gainsboro;
    border-radius: 53px;
}
label {
  position: absolute;
  top: 0;
  display: block;
  transition: 0.2s;
  font-size: 1rem;
  color: $gray;
}
  </style>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
        <a class="nav-link" href="/account">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href='/profile'>Profile</a>
      </li>

      <li class="nav-item ">
        <a class="nav-link" href='/post'>Posts</a>
      </li>
    <li class="nav-item ">
    <form method='POST' action="{% url 'logoutuser' %}" class='ml-3' >
         {% csrf_token %}
      <button type='submit' class='btn btn-dark'>Logout</button></form>
  </li>
     </ul>
     </div>

</nav>
  <div class='container'>
  <div class="row">
	<div class="col-md-3">
		<div class="card card-body">
			<hr>
			<img class="profile-pic" src="{{request.user.customer.profile_pic.url}}" >
		  
		</div>
	</div>
    <div>
  <h2> {{ user.username }} Details</h2>
 <form method = "post" enctype="multipart/form-data"  action='' > 
        {% csrf_token %} 
        {{ form2.as_p }} 
        <button  class='btn'type="submit">Upload</button> 
    </form>
     <a   href='/post'><input  class="register" type="button" value="Get Started"> </a> 
    </body>
    </div>
    </html>

templates/social_app/index3.html
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Google Registration</title>
  </head>
  <style>
label {
  font-family: 'Roboto', sans-serif;
  font-size: 1.2rem;
  margin-left: 2rem;
  margin-top: 0.7rem;
  transition: all 0.3s;
  transform: translateY(0rem);
}
button.btn.btn-lg.btn-success {
    display: inherit;
    margin: auto;
}

  </style>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
        <a class="nav-link" href="/account">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href='/profile'>Profile</a>
      </li>

      <li class="nav-item ">
        <a class="nav-link" href='/post'>Posts</a>
      </li>
    <li class="nav-item ">
    <form method='POST' action="{% url 'logoutuser' %}" class='ml-3' >
         {% csrf_token %}
      <button type='submit' class='btn btn-dark'>Logout</button></form>
  </li>
     </ul>
     </div>

</nav>
<h2 align='center'>Upload Your Timeline, {{ user.username }} </h2>
    <div class="container">
      
        <form action="." method="post"  enctype="multipart/form-data" class="form-horizontal">
        <div class="form-group">
            {% csrf_token %}
            {{form.as_p}}
           
            <button type="submit" align='center' class="btn btn-lg btn-success">Upload</button>
            </div>
        </form>
       
        <hr>
        {% for x in img %}
        {% if forloop.first %}<div class="row ">{% endif %}
            <div class="col-lg-4 col-md-4 col-12" >
        <div class="text-center mt-2">
            <img src="{{x.image.url}}"  height="70%" width="70%" class="img-thumbnail" alt="...">
            <h2 class="text-center" >{{x.caption}}</h2></div>
            </div>
            {% if forloop.counter|divisibleby:3 %}
        </div>
        <div class=row>{% endif %}
        
            {% if forloop.last %}</div>{% endif %}
    
        {% endfor %}
    </div>
    </body>
    </html>